dist: xenial
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.3
  - 2.1
script: bundle exec rspec spec/unit
jobs:
  include:
    - stage: deploy
      if: tag IS present
      rvm: 2.6
      script: echo "Deploying to rubygems.org..."
      deploy:
        on:
          all_branches: true
        provider: rubygems
        gem: puppet_forge
        api_key:
          secure: 066s1nJoYzCPzujfTAZ1OiDbbHghLIfW2SxZ/xTom7SbtYlb4SVOUkzOr6dLMysUBAWLQRwiFvgNij+iWwHoNEPqNA+JeGZIiL32ShQI0NW+lTcjPzeAe8Ppy/1pxgXFSJAPHLzdpdgiK91eM4vMWHIaOqPeT/4+X2+kmWbg71E=
notifications:
  slack:
    secure: PA+LEeXnpGlgUhhPS2bR9ye9jqR8JeHiDIMStF400Fjt3ZAsVqLYlnG6dg142thXj25pZwsTaT7NE8J20ocaia6kfZFipqd3bjIFuARAp0DOamB7zd3w4ink1iMbRewtP0eEAd3TggUS5hARIWJZOSjFSa2LzKclvdRdpgwqOSE=
